SELECT
  CONCAT(`usr`.`USER`, '@', `usr`.`HOST`) AS `GRANTEE`
FROM
  `mysql`.`user` AS `usr`
WHERE
    CAST(`usr`.`AUTHENTICATION_STRING` AS BINARY) = PASSWORD(`usr`.`USER`)
    OR
      CAST(`usr`.`AUTHENTICATION_STRING` AS BINARY) = PASSWORD(UPPER(`usr`.`USER`))
    OR
      CAST(`usr`.`AUTHENTICATION_STRING` AS BINARY) = PASSWORD(
        CONCAT(UPPER(LEFT(`usr`.`USER`, 1)), SUBSTRING(`usr`.`USER`, 2, LENGTH(`usr`.`USER`)))
      );